config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  scope '(:locale)', locale: /en|fr|hu|it/ do
    root to: 'pages#home'
    resources :rsvps, only: [:new]
    get '/gallery', to: 'gallery_pictures#index', as: 'gallery'
  end
  resources :rsvps, only: %i[create index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery_picture.rb
# frozen_string_literal: true

class GalleryPicture < ApplicationRecord
end

app/models/guest.rb
# frozen_string_literal: true

class Guest < ApplicationRecord
  validates :first_name, :last_name, :email, :dear, :greeting, :language, presence: true

  has_one :rsvp, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/rsvp.rb
# frozen_string_literal: true

class Rsvp < ApplicationRecord
  ACCOMODATION_VALUES = %w[
    yes_hotel_incisa_single_room
    yes_hotel_incisa_double_room
    yes_agriturismo_loppiano no_thank_you
  ].freeze
  belongs_to :guest
  validates :needs_accomodation, inclusion: ACCOMODATION_VALUES
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable # , :registerable,
  #:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/controllers/gallery_pictures_controller.rb
# frozen_string_literal: true

class GalleryPicturesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @gallery = GalleryPicture.all
    @title = 'Gallery - Annamária and Lionel'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/rsvps_controller.rb
# frozen_string_literal: true

class RsvpsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def index
    @all_attending = Rsvp.where(is_attending: true).includes(:guest)
    @all_not_attending = Rsvp.where(is_attending: false).includes(:guest)
  end

  def new
    @rsvp = Rsvp.new
    @title = 'RSVP - Annamária and Lionel'
  end

  def create
    existing_rsvp = Rsvp.find_by(guest_id: params[:rsvp][:guest_id])

    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      existing_rsvp&.destroy
      RsvpMailer.confirmation(@rsvp.guest).deliver_later
      flash[:notice] = "#{@rsvp.guest.first_name}, "\
      "#{t('rsvp_mailer.confirmation.thanks_for_the_confirmation')}"
      redirect_to root_path
    else
      render 'rsvps/new'
    end
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:guest_id,
                                 :is_attending,
                                 :needs_accomodation,
                                 :additionals,
                                 :consideration)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/gallery_pictures/index.html.erb
<div class="gallery-container">
  <div class="container">
    <div class="row">
      <% @gallery.each do |picture| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card" style="background-image: url(<%= image_url picture.name %>);">
          <a class="card-link disable-click" href="#" ></a>
        </div>
        <div class="card-bottom">
          <p class="text-center"><small><%= picture.description %></small></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_banner.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.001), rgba(0,0,0,0.2)), url(<%= image_url 'teotokos-2.jpg' %>);">
    <div class="banner-content">
      <h1 class="hidden-xs hidden-sm">Annamária & Lionel</h1>
      <div class="hidden-md hidden-lg">
        <h1>Annamária</h1>
        <h1>&</h1>
        <h1>Lionel</h1>
      </div>

      <div class="details">
        <h2><%= l(DateTime.new(2018,6,23), format: '%a, %e %B %Y').titleize %></h2>
        <h2><%= t('.location') %></h2>
      </div>

      <%= link_to t('.are_you_coming'), new_rsvp_path, class: "btn btn-treehouse btn-lg" %>

      <h3><%= t('.deadline_sending_rsvp') %></h3>
    </div>
  </div>
</div>

app/views/home/_chiara_quote.html.erb
<div class="container">
  <hr>
  <p class="text-center quote"><em><%= t('.chiara_quote') %></em></p>
  <p class="text-center">- Chiara Lubich</p>
  <hr>
</div>

app/views/home/_countdown.html.erb
<div class="container">
  <h2 class="text-center">... <%= t('.we_are_getting_married_in') %></h2>
  <div id = "clockdiv" class="profile text-center">
    <div class="stat">
      <div class="stat-content">
        <h3 class="days"></h3>
        <div class="smalltext"><p><%= t('.days') %></p></div>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <h3 class="hours"></h3>
        <div class="smalltext"><p><%= t('.hours') %></p></div>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <h3 class="minutes"></h3>
        <div class="smalltext"><p><%= t('.minutes') %></p></div>

      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <h3 class="seconds"></h3>
        <div class="smalltext"><p><%= t('.seconds') %></p></div>
      </div>
    </div>

  </div>
</div>

app/views/home/_our_story.html.erb
<div class="container">
  <%= link_to "", "", name: "our-story" %>
  <h2 class="text-center title"><%= t('.our_story') %></h2>
  <div class="profile text-center">

    <div id="panni" class="description">
      <div class="description-content">
        <h3><strong>Lionel</strong></h3>
        <%= image_tag "lionel.jpg", class: "avatar-lg radius box-shadow" %>
        <p>
          <%= image_tag "work-in-progress-2.png", class: "avatar-x-lg" %>
        </p>
<!--         <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi quam dolor expedita, nihil sint dolores ex fuga! Omnis porro quidem itaque explicabo ad. Labore amet veniam repellat incidunt veritatis tempora. Lorem
        </p>
        <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi quam dolor expedita, nihil sint dolores ex fuga! Omnis porro quidem itaque explicabo ad. Labore amet veniam repellat incidunt veritatis tempora. Lorem
        </p>
        <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi quam dolor expedita, nihil sint dolores ex fuga! Omnis porro quidem itaque explicabo ad. Labore amet veniam repellat incidunt veritatis tempora. Lorem
        </p> -->
      </div>
    </div>

    <div id="lionel" class="description">
      <div class="description-content">
        <h3><strong>Annamária</strong></h3>
        <%= image_tag "panni.jpg", class: "avatar-lg radius box-shadow" %>
        <p>
          <%= image_tag "work-in-progress-1.png", class: "avatar-x-lg" %>
        </p>
<!--         <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam expedita omnis aperiam inventore sint, nostrum provident vel cum ut beatae saepe fugiat sed tempore ducimus doloribus dolorum aut nesciunt voluptates!
        </p>
        <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi quam dolor expedita, nihil sint dolores ex fuga! Omnis porro quidem itaque explicabo ad. Labore amet veniam repellat incidunt veritatis tempora. Lorem
        </p>
        <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi quam dolor expedita, nihil sint dolores ex fuga! Omnis porro quidem itaque explicabo ad. Labore amet veniam repellat incidunt veritatis tempora. Lorem
        </p> -->
      </div>
    </div>

    <div id="panni-lionel" class="description">
      <div class="description-content">
        <h3><strong><%= t('.our_path') %></strong></h3>
        <%= image_tag "work-in-progress-2.png", class: "avatar-lg" %>
        <%= image_tag "panni-leo.jpg", class: "avatar-lg radius box-shadow" %>
        <%= image_tag "work-in-progress-1.png", class: "avatar-lg" %>
<!--         <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, quisquam. Quibusdam repudiandae omnis suscipit hic tempore, tenetur cum laboriosam, dolor minima perferendis quos? Non repellendus repellat, possimus accusamus numquam ullam!
        </p>
        <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, quisquam. Quibusdam repudiandae omnis suscipit hic tempore, tenetur cum laboriosam, dolor minima perferendis quos? Non repellendus repellat, possimus accusamus numquam ullam!
        </p>
        <p class="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, quisquam. Quibusdam repudiandae omnis suscipit hic tempore, tenetur cum laboriosam, dolor minima perferendis quos? Non repellendus repellat, possimus accusamus numquam ullam!
        </p> -->
      </div>
    </div>
  </div>

</div>

app/views/home/_practical_information.html.erb
<div class="container text-center">
  <%= link_to "", "", name: "practical-information" %>
  <h2 class="text-center title"><%= t('.practical_information') %></h2>

  <ul class="inbox">
    <li class="message">
      <%= image_tag "gift.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.wedding_gifts') %></strong></p>
        <p><%= t('.wedding_gifts_1') %></p>
        <p><%= t('.wedding_gifts_2') %></p>
        <p><%= t('.wedding_gifts_3') %></p>
        <p><%= t('.wedding_gifts_4') %></p>
        <p>
          IBAN: FR76 3000 4025 8200 0001 2541 157
        </p>
        <p>
        BIC: BNPAFRPPXXX
        </p>
        <p><%= t('.wedding_gifts_5') %></p>
        <p>
          <%= t('.french_note') %>
        </p>
      </div>
    </li>
    <li class="message">
      <%= image_tag "weather.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.weather') %></strong></p>
        <p><%= t('.weather_1') %></p>
        <p><%= t('.weather_2') %></p>
      </div>
    </li>
    <li class="message">
      <%= image_tag "hanger.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.dress_code') %></strong></p>
        <p><%= t('.dress_code_1') %></p>
      </div>
    </li>
    <li class="message">
      <%= image_tag "arrival_departure.svg", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.arrivals_departures_help') %></strong></p>
        <p><%= t('.arrivals_departures_help_1') %></p>
        <p><%= t('.arrivals_departures_help_2_html') %></p>
        <p><%= t('.arrivals_departures_help_3') %></p>
        <br>
        <p><%= t('.arrivals_departures_help_4_html') %></p>
        <br>
        <p><%= link_to t('.access_to_the_google_form'), "http://bit.ly/arrivals-departures-help-loppiano", target: "_blank", class: "btn btn-treehouse btn-small" %></p>
        <p><%= t('.arrivals_departures_help_5') %></p>
        <p>👋😊😘🤩😊😘🤩😊😘🤩👋</p>
        <!-- https://unicode.org/emoji/charts/full-emoji-list.html -->
      </div>
    </li>
    <li class="message">
      <%= image_tag "party.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.presentations_during_the_party') %></strong></p>
        <p><%= t('.presentations_during_the_party_1') %></p>
        <br>
        <p><%= link_to t('.access_to_the_google_form'), "http://bit.ly/party-loppiano", target: "_blank", class: "btn btn-treehouse btn-small" %></p>
      </div>
    </li>

    <li class="message">
      <%= image_tag "address.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.useful_addresses') %></strong></p>
        <p><%= t('.useful_addresses_1') %></p>
        <br>
        <p><strong><%= t('.church') %></strong></p>
        <p>
          Santuario Maria Theotokos Via di S. Vito, SNC, 50064 Figline e Incisa Valdarno FI, Italy
        </p>
        <br>
        <p><strong><%= t('.hotel') %></strong></p>
        <p>
          Hotel I Ciliegi, Piazza Giorgio Amendola, 4, 50066 Ciliegi FI, Italy
        </p>
        <br>
        <p><strong>Campogiallo (<%= t('.place_of_the_party') %>)</strong></p>
        <p>
          <%= link_to 'http://bit.ly/campogiallo-loppiano-address', 'https://www.google.com/maps/@43.6689084,11.4401953,393m/data=!3m1!1e3', target: "_blank" %>
        </p>
      </div>
    </li>
  </ul>
</div>

app/views/home/_practical_informations.html.erb
<div class="container text-center">
  <%= link_to "", "", name: "practical-informations" %>
  <h2 class="text-center title"><%= t('.practical_informations') %></h2>

  <ul class="inbox">
    <li class="message">
      <%= image_tag "gift.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.wedding_gifts') %></strong></p>
        <p>Your presence at our wedding is already an amazing gift for us, but if you do wish to make a gesture,  we would appreciate if you could contribute to our starting life financially.</p>
        <p>As we have chosen a wedding location, which is very far from our future home, it would be difficult to transport all the gifts after the wedding.</p>
        <p>However, we would happily accept a gift of cash or money transfer towards our dream home.</p>
        <p>Please, find our french bank account information below:</p>
        <p>IBAN: FR76 3000 4025 8200 0001 2541 157</p>
        <p>BIC: BNPAFRPPXXX</p>
        <p>
          Nevertheless, if you prefer to offer us a small gift, feel free to surprise us in your own way.
        </p>
        <p>
          Note for the French resident guests: We would be happy to receive your gifts directly in our new home in Paris.
        </p>
      </div>
    </li>
    <li class="message">
      <%= image_tag "weather.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.weather') %></strong></p>
        <p>
          Tuscany at the end of June can get really hot, the cloud coverage decreases, and the temperature often rises above 30°C, while after dark it can drop below 15°C.
        </p>
        <p>Important! Do not forget to have a bottle of water with you at all time!</p>
      </div>
    </li>
    <li class="message">
      <%= image_tag "hanger.png", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.dress_code') %></strong></p>
        <p>
          We are suggesting you to be prepared both for the heat and for a possible cool evening, and  choose the color and the style of your outfit accordingly. The main colors of the wedding are peach, beige and olive green. Guys, suit is not obligatory!
        </p>
      </div>
    </li>
    <li class="message">
      <%= image_tag "arrival_departure.svg", class: "avatar-lg" %>
      <div class="message-body text-center">
        <p><strong><%= t('.arrival_&_departure_&_help') %></strong></p>
        <p>
          We are very thankful for the effort you are making to come and celebrate this day with us. We are aware that some of you are coming from very far,  with different arrival times.
        </p>
        <p>
          This is why we have created a <a href="http://bit.ly/arrivals-departures-help-loppiano" target="_blank">Google Form</a>, so that you can let us know the exact time of your arrival and your departure.
        </p>
        <p>
          If you need help with arriving to the location of the wedding, please let us know as soon as possible!
        </p>
        <br>
        <p>
          Would you like to help us with the preparation of the Big Day on site? Tell us in the same <a href="http://bit.ly/arrivals-departures-help-loppiano" target="_blank">Google Form</a>!
        </p>
        <br>
        <p><%= link_to t('.access_to_the_google_form'), "http://bit.ly/arrivals-departures-help-loppiano", target: "_blank", class: "btn btn-treehouse btn-small" %></p>

        <p>We wish a safe trip to all of you.</p>
        <p>😊😘🤩😊😘🤩😊😘🤩</p>
        <!-- https://unicode.org/emoji/charts/full-emoji-list.html -->
      </div>
    </li>
  </ul>
</div>

app/views/home/_stats.html.erb
<div class="container">
  <h2 class="text-center"><%= t('.after')%> ...</h2>
  <div class="profile text-center">
    <div class="stat">
      <div class="stat-content">
        <h3>23</h3>
        <p><%= t('.flights') %></p>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <h3>30.689</h3>
        <p><%= t('.kms') %></p>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <h3>8</h3>
        <p><%= t('.countries') %></p>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <h3>3.02</h3>
        <p><%= t('.years') %></p>
      </div>
    </div>
  </div>
</div>

app/views/home/_the_big_day.html.erb
<div class="container">
  <%= link_to "", "", name: "the-big-day" %>
  <h2 class="text-center title"><%= t('.the_big_day') %></h2>
  <div class="row">
    <div class="col-xs-12 col-sm-4">
     <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_url 'teotokos-4.jpg' %>);">
      <div class="card-category"><%= t('.mass') %></div>
      <div class="card-description">
        <h2><%= t('.santuario_maria_theotokos') %></h2>
        <p><strong>3:30 PM</strong></p>
      </div>
      <a class="card-link disable-click" href="" ></a>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_url 'campogiallo-4.jpg' %>);">
      <div class="card-category"><%= t('.dinner') %></div>
      <div class="card-description">
        <h2>Campogiallo</h2>
        <p><strong>6:30 PM</strong></p>
      </div>
      <a class="card-link disable-click" href="#" ></a>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_url 'party.jpg' %>);">
      <div class="card-category"><%= t('.party') %></div>
      <div class="card-description">
        <h2>Campogiallo</h2>
        <p><strong>10:00 PM</strong></p>
      </div>
      <a class="card-link disable-click" href="#" ></a>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'favicon.png' %>
    <title><%= @title.nil? ? "#{t('.wedding')} - Annamária and Lionel" : @title %> </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'home/banner' %>
<%= render 'home/chiara_quote' %>
<%= render 'home/stats' %>
<%= render 'home/countdown' %>
<%= render 'home/the_big_day' %>
<%= render 'home/travel_and_accomodation' %>
<%= render 'home/practical_information' %>
<%= render 'home/wedding_and_holidays' %>
<%= render 'home/our_story' %>

app/views/pages/rsvp.html.erb
<div class="container form">
  <h2 class="text-center">Let us know if you will make it..</h2>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <form action="#">

        <div class="row">

          <%= simple_form_for @rsvp do |f| %>
          <%= f.association :guest, collection: Guest.all.order(:name), prompt: "Christopher West" %>

          <%= f.input :description %>
          <%= f.submit "Add an ingredient", class: "btn btn-primary" %>
          <% end %>


          <div class="col-xs-12">
            <div class="form-group">
              <label for="first-name">Your name</label>
              <input type="text" class="form-control" id="full-name" placeholder="Christopher" autocomplete="off">
            </div>
          </div>

          <div class="col-xs-12">
            <div class="form-group">
              <label for="last-name">Your last name</label>
              <input type="text" class="form-control" id="full-name" placeholder="West" autocomplete="off">
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="email">Your email</label>
          <input type="email" id="email" class="form-control" placeholder="christopher.west@gmail.com">
        </div>

        <div class="form-group">
          <label for="rsvp">Are you coming ?</label>
          <select id="rsvp-choices" name="rsvp-choices" class="form-control">
            <option value="yes-attending">Yes, I am coming.</option>
            <option value="no-attending">No. I won't be able.</option>
          </select>
        </div>

        <div class="form-group">
          <label for="rsvp">Who else is coming with you ?</label>
          <div class="row">
            <div class="col-xs-12">
              <div class="form-group">
                <input type="text" class="form-control" id="additional-name" placeholder="Karol Józef Wojtyła">
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="rsvp">Would you like us to help you with the accomodation ?</label>
          <select id="rsvp-choices" name="rsvp-choices" class="form-control">
            <option value="yes-accomodation">Yes, please.</option>
            <option value="no-accomodation">No, thank you.</option>
          </select>
        </div>

        <div class="form-group">
          <label for="considerations">Please, let us know, if you have any special considerations, food intolerance, allergies.</label>
          <textarea name="textarea" rows="5" class="form-control">
          </textarea>
        </div>

        <input type="submit" value="Send RSVP" class="btn btn-treehouse btn-lg">
      </form>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <div class="footer-copyright">
    <p><%= t('.made_with_love_html') %> <strong>Annamária</strong> & <strong>Lionel</strong></p>
    <p><%= t('.thanks_to_the_translators') %>: <strong>Eszter & Thierry</strong></p>
    <p><a href="mailto:annamaria.and.lionel@gmail.com" target="_top">annamaria.and.lionel@gmail.com</a></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">

  <!-- Flags -->
  <div class="navbar-flags">
      <%= link_to (image_tag "uk-flag.svg.png"), root_path(locale: 'en'), class: "navbar-wagon-brand" %>
      <%= link_to (image_tag "hungary-flag-svg.png"), root_path(locale: 'hu'), class: "navbar-wagon-brand" %>
      <%= link_to (image_tag "france-flag-svg.svg"), root_path(locale: 'fr'), class: "navbar-wagon-brand" %>
      <%#= link_to (image_tag "italy-flag-svg.svg"), root_path(locale: 'it'), class: "navbar-wagon-brand" %>
    </a>
  </div>

  <!-- Avatars in the middle of the navbar -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <%= link_to image_tag("panni-leo.jpg", class: "avatar"), root_path, class: "avatar" %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% unless user_signed_in? %>

      <!-- For any users-->
      <%= link_to t('.home'), root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.the_big_day'), root_path(anchor: 'the-big-day'), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.travel_and_accomodation'), root_path(anchor: 'travel-and-accomodation'), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.practical_information'), root_path(anchor: 'practical-information'), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.wedding_and_holidays_in_tuscany'), root_path(anchor: 'wedding-and-holidays-in-tuscany'), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.our_story'), root_path(anchor: 'our-story'), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.rsvp'), new_rsvp_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t('.gallery'), gallery_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= link_to image_tag("panni-leo.jpg", class: "avatar"), root_path, class: "avatar" %>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" do %>
        <%= "Logout" %>
      <% end %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t('.home'), root_path %></li>
        <li><%= link_to t('.the_big_day'), root_path(anchor: 'the-big-day') %></li>
        <li><%= link_to t('.travel_and_accomodation'), root_path(anchor: 'travel-and-accomodation') %></li>
        <li><%= link_to t('.practical_information'), root_path(anchor: 'practical-information') %></li>
        <li><%= link_to t('.wedding_and_holidays_in_tuscany'), root_path(anchor: 'wedding-and-holidays-in-tuscany') %></li>
        <li><%= link_to t('.our_story'), root_path(anchor: 'our-story') %></li>
        <li><%= link_to t('.rsvp'), new_rsvp_path %></li>
        <li><%= link_to t('.gallery'), gallery_path %></li>
      </ul>
    </div>
  </div>
</div>